from discord.ext import commands
import random

class Piada(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
    @commands.command()
    async def piada(self, ctx):
      piadas = [
    "Por que o jacaré tirou o filho da escola? Porque ele réptil de ano!",
    "Por que o menino estava falando ao telefone deitado? Porque estava fazendo uma ligação à cobrar!",
    "O que é um pontinho amarelo no canto da parede? Uma bactéria com hepatite.",
    "Como o Batman faz para que abram a batcaverna? Ele batpala.",
    "Por que a vaca foi para o espaço? Para visitar a Via Láctea.",
    "Qual é o cúmulo do absurdo? Colocar um DVD de corrida em câmera lenta para não cansar o carro.",
    "Por que a galinha atravessou a estrada? Para chegar do outro lado.",
    "O que o tomate disse para o outro? Não se preocupe, ketchup.",
    "Qual é o café mais perigoso do mundo? O assassinato.",
    "Como o eletricista atende o telefone? Alô, quem fala?",
    "Por que o lápis foi preso? Porque ele apontou para alguém.",
    "Como se chama um boi que toca violino? Boi-linista.",
    "Por que o computador foi ao médico? Porque estava com um vírus!",
    "Por que o peixe não gosta de matemática? Porque tem medo de peixe quadrado.",
    "Qual o animal mais antigo do mundo? A zebra, porque é em preto e branco!",
    "O que é um pontinho vermelho voando no espaço? Um moranguito espacial.",
    "O que o 0 disse para o 8? Que cinto maneiro!",
    "Como o relógio se apresenta? Muito prazer, Tik Tak.",
    "O que é um astrólogo preso? Um signo fechado.",
    "Por que o esqueleto não briga? Porque ele não tem coragem.",
    "Como os oceanos dizem oi? Eles mandam uma onda.",
    "Por que a abelha sempre é promovida? Porque ela está sempre no 'mel'hor desempenho.",
    "O que o código disse para o bug? Você não faz parte do meu escopo!",
    "Por que os programadores preferem o escuro? Porque a luz atrapalha o terminal.",
    "Como o desenvolvedor termina um relacionamento? Com um commit final.",
    "Por que o Java foi ao terapeuta? Porque ele tinha problemas de herança.",
    "Por que o Python foi rejeitado na balada? Porque ele era muito interpretado.",
    "Por que o HTML foi preso? Porque ele estava marcando bobeira.",
    "Qual o contrário de papelada? Pau pé duro.",
    "O que o peixe disse quando bateu na parede? Ai meu Deus, uma barragem!",
    "O que é verde e fica no canto da sala? Um cantope verde.",
    "Por que o coelho atravessou a estrada? Porque era a vez dele no jogo.",
    "Como o pato atende o telefone? Quá?",
    "O que o milho falou para o outro? Milhó, beleza?",
    "Como se chama um cão mágico? Labracadabrador.",
    "Como o Hulk chama a mãe dele? Mãe verde!",
    "Como se despede um químico? Ácido vê!",
    "Por que o rei foi ao dentista? Para cuidar do seu reinado.",
    "O que o astronauta disse ao quebrar a nave? Houston, temos um problema.",
    "Por que o livro se apaixonou pela biblioteca? Porque ela era cheia de histórias.",
    "Como chama o boi que não faz nada? Boi lerdo.",
    "Por que o pneu se matou? Porque ele estava cheio!",
    "O que o escorregador falou para a criança? Desce daí!",
    "A mãe do Rafa é tão loira que colocou o celular no modo avião e jogou pela janela.",
    "A mãe do Rafa é tão rodada que quando ela deita, o Google calcula rota.",
    "A mãe do Rafa é tão aberta que o Discord pensou que era uma porta de servidor.",
    "A mãe do Rafa é tão feia que quando entrou no servidor, o bot deu ban automático.",
    "A mãe do Rafa é tão burra que tentou instalar o ar-condicionado com pendrive."
    "Kamikaze (Rafa) é tão lerdo que o Wi-Fi dele demora até pra desconectar.",
    "Kamikaze (Rafa) é tão desligado que esquece a senha até do próprio PC.",
    "Kamikaze (Rafa) é tão azarado que se colocar sal na comida, o sal reclama.",
    "Kamikaze (Rafa) é tão perdido que entrou no servidor errado e perguntou onde era a reunião.",
    "Kamikaze (Rafa) é tão viciado em café que já tentou debugar o sono.",
    "Por que o vampiro sempre se dá bem? Porque ele tem um mordida de sorte.",
    "O que o zero falou para o oito? Adorei seu cinto novo!",
    "Por que o livro de história está sempre cansado? Porque ele vive no passado.",
    "Como o pão chama o queijo? Você é o meu par perfeito!",
    "Qual é o animal que gosta de música? O tambo-rino.",
    "Por que a aranha é um ótimo programador? Porque ela sabe fazer muitas teias.",
    "O que o relógio falou para o calendário? Seu tempo está contado.",
    "Por que o cavalo foi ao cinema? Porque queria ver um filme de ação.",
    "O que o computador faz quando está com frio? Ele fecha as janelas.",
    "Por que o coelho não conta segredos? Porque ele é todo ouvidos.",
    "Como a cebola pediu desculpas? Chorando muito.",
    "Qual é o café mais doce do mundo? O café com açúcar de piada.",
    "Por que o elefante não usa computador? Porque tem medo do mouse.",
    "O que a nuvem disse para o raio? Você me dá um choque.",
    "Por que o livro de matemática estava triste? Porque tinha muitos problemas.",
    "O que a árvore falou para o vento? Pare de me balançar!",
    "Como o sapo termina uma conversa? Com um Até mais, amigo.",
    "Por que o cachorro gosta de usar computador? Porque ele adora clicar no mouse.",
    "O que o sorvete disse para o sol? Me derrito por você!",
    "Por que o peixe não gosta de jogar cartas? Porque tem medo de ser pego.",
    "Qual é a comida preferida dos fantasmas? Buuuritos.",
    "Por que o pato foi ao médico? Porque ele estava gripado.",
    "O que o tomate falou para o pepino? Vamos fazer uma salada juntos!",
    "Como a formiga se esconde? Ela é muito pequena para ser vista.",
    "Por que o sapo pulou da ponte? Para ir ao outro lado.",
    "O que o sol falou para a lua? Você ilumina minha noite.",
    "Por que a zebra é listrada? Para se esconder na selva.",
    "O que o lápis disse para o papel? Vamos fazer arte juntos!",
    "Por que a girafa tem o pescoço comprido? Para alcançar as folhas mais altas.",
    "Como o morcego se orienta? Com o eco.",
    "O que o pão falou para a manteiga? Você me completa.",
    "Por que o rato tem medo do gato? Porque ele é maior e mais forte.",
    "O que o computador disse para o usuário? Estou travando de tanto trabalhar.",
    "Por que a estrela não brilha durante o dia? Porque o sol ofusca ela.",
    "O que o relógio falou para o ponteiro? Vamos girar juntos.",
    "Por que o leão é o rei da selva? Porque é o mais forte.",
    "Como a abelha faz mel? Trabalhando muito.",
    "O que a chuva falou para o guarda-chuva? Você me protege.",
    "Por que o peixe não nada para trás? Porque não tem ré!",
    "O que o sapo disse para a mosca? Você é meu almoço.",
    "Por que o gato gosta de dormir? Porque é preguiçoso.",
    "O que a borboleta disse para a lagarta? Você vai se transformar.",
    "Por que a coruja é sábia? Porque ela vigia à noite.",
    "O que o elefante falou para o rato? Você é pequeno, mas valente.",
    "Por que o cavalo gosta de correr? Porque ele tem muita energia.",
    "O que o leão falou para a zebra? Você tem um estilo listrado incrível.",
    "Por que o coelho gosta de cenoura? Porque é doce e saudável.",
    "O que o passarinho falou para o ninho? Você é minha casa."
    ]
      await ctx.send(random.choice(piadas))

async def setup(bot):
   await bot.add_cog(Piada(bot))

      

    

